#! venv/bin/python3.10
from random import randint, choice

names = [
    'Иван',
    'Дима',
    'Максим',
    'Коля',
    'Михаил',
    'Терентий',
    'Маша'
]


class Game(object):
    _instance = None

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self, number_of_npc: int):
        self.number_of_NPC = number_of_npc
        self.players = []
        for i in range(number_of_npc):
            self.players.append(NPC(choice(names) +"_"+ str(i+1)))

    def start(self):
        are_alive = True
        round = 0
        while are_alive:

            round += 1
            temp = []
            for i in range(len(self.players)):
                if self.players[i].is_alive:
                    temp.append(self.players[i])
            self.players = temp
            print(f"Стартует раунд {round}")
            if len(self.players) > 1:
                for npc in self.players:
                    if npc.is_alive:
                        npc.attack(target=npc.get_target(self.players))

            else:
                return self.players[0]






class NPC(object):
    def __init__(self, name: str):
        self.hp = randint(1, 100)
        self.damage = randint(1, 50)
        # self.target = None
        self.is_alive = True
        self.name = name
        print(f"Новый боец по имени: {self.name}, {self}\n"
              f"У него: {self.hp} здоровья\n"
              f"И {self.damage} урон")

    def get_target(self, players: list):
        while True:
            target = choice(players)
            if not target == self and target.is_alive:
                print(f"{self.name} выбрал цель {target.name}")
                return target

    def attack(self, target: "NPC"):
        # if not self.target:
        #    self.target = target
        print(f"{self.name} нанес  {target.name}  {self.damage} урона")
        target.attacked(self.damage)

    def attacked(self, damage: int):
        if self.hp > damage:
            self.hp = self.hp - damage
        else:
            self.is_alive = False
            print(f"{self.name} died!")


class Players_list():
    def __int__(self, players):
        self.players = players

    def player_dies(self):
        pass



if __name__ == "__main__":
    print("Welcome to the Game!")
    #game = Game(int(input("Введите количество игроков: ")))
    g = Game(0)
    print(g)
    game = Game(10)
    print(game)
    winner = game.start()
    print(f"{winner.name} победил!!!")

